version: '3.8'

networks:
  monitoring:
    driver: bridge

services:
  app:
    container_name: app
    build:
      context: app
    volumes:
      - ./app/src:/app/src
    ports:
      - 5001:5001
      - 9200:9200
      - 9229:9229
    networks:
      - monitoring

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - 9090:9090
    networks:
      - monitoring
    depends_on:
      - app

  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter:latest
    ports:
      - 9100:9100
    networks:
      - monitoring
    depends_on:
      - prometheus

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - 3000:3000
    networks:
      - monitoring
    depends_on:
      - node-exporter

