{
 "title": "Nodejs Application",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Versión de Nodejs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(nodejs_version_info) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Uso de CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(process_cpu_user_seconds_total[1m]) * 100",
     "legendFormat": "Aplicación"
    },
    {
     "expr": "irate(process_cpu_system_seconds_total[1m]) * 100",
     "legendFormat": "Sistema"
    }
   ]
  },
  {
   "title": "Uso de memoria",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "Memoria de proceso" },
    { "expr": "nodejs_heap_size_total_bytes", "legendFormat": "Tamaño de pila (Total)" },
    { "expr": "nodejs_heap_size_used_bytes", "legendFormat": "Tamaño de pila (En uso)" },
    { "expr": "nodejs_external_memory_bytes", "legendFormat": "Memoria externa" }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(avg by (instance) (irate(process_cpu_seconds_total[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uso de memoria externa",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(nodejs_external_memory_bytes) by (route)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tiempos de Garbage Collector",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "(avg by (kind) (irate(nodejs_gc_duration_seconds_bucket[$__rate_interval])) * 100)",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(responses_times_count[1m])) * 60",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Tiempo de Respuesta (Media)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(responses_times_sum[$__rate_interval]) / rate(responses_times_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tiempo de Respuesta (Percentil 5)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "responses_times{quantile=\"0.05\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Tiempo de Respuesta (Mediana)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "responses_times{quantile=\"0.5\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Tiempo de Respuesta (Percentil 95)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "responses_times{quantile=\"0.95\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Tiempo de Respuesta (Percentil 9.99)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "responses_times{quantile=\"0.999\"}",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}